# Generated by Django 6.0 on 2026-03-10 15:21

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Google Maps link to the turf location', max_length=500),
        ),
    ]
