# Generated by Django 6.0 on 2026-03-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_turf_google_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.sport'),
        ),
    ]
